### ISSUE TITLE
NoCoverageData with a no_std kernel

### ISSUE THREAD

**Issue by jschwe** [Amanieu/minicov#1]
Hi,

I'm currently trying to get some code coverage for a rust no_std kernel. However I've been running into some issues and I hoped you might be able to help. Since I'm not using libc (kernel starts with a custom `_start` function) I copied the `run_static_constructors()` function into my kernel. However when debugging with gdb `__init_array_start ` and `__init_array_end` seem to be set to the same address at compile time. When compiling with optimization level of 1 the end variable is even optimized out. I checked the executable with `objdump` and it shows me the same address for both symbols.

I'm currently using a reduced example where I'm doing the following:
- My test application (basically hello world + a couple of branches) is compiled with minicov as a dependency and the flags `"-Zprofile -Zno-profiler-runtime -Clink-dead-code -Copt-level=0 -Coverflow-checks=off"` injected via a `RUSTC_WRAPPER`.
- My kernel and everything else is compiled without these flags. Additionally I copied the `run_static_constructors()` function into my kernel so that everything is initialized. 
- kernel and test application are linked together via cargo / rust-lld and executed with qemu.
- The application panics at the end due to `NoCoverageData` (`minicov::capture_coverage().unwrap()`) . Since the init doesn't seem to work this is not so surprising. 
- I also tried without the `run_static_constructors()` in my kernel and instead called `minicov::run_static_constructors()` at the beginning of the main function of my test application. That didn't work either though. 

This leads me to the following questions:

- There are no `.gcno` files created when building my test application with minicov, is this expected? When building my kernel as a library (without minicov but with `-Zprofile`) I verified that one `.gcno` file gets created. 
- If I specify minicov as a dependency of the crate I'm trying to generate code coverage for, won't this lead to the `llvm_gcda_xxx` functions provided by minicov also being compiled with `-Zprofile`?
- Where exactly are the `__init_array_start` and end functions defined? Is it correct to assume that they must be called before any code that was instrumented with `-Zprofile` is executed?

**Comment by Amanieu** [comment]
- If no gcno files are being generated it means that -Zprofile isn't getting passed to rustc. Make sure the flags are used for compiling all crates not just minicov.
- It doesn't matter if minicov itself is compiled with `-Zprofile`, it will still work.
- The `__init_array_start` and `__init_array_end` symbols are automatically generated by the linker from the `.init_array` section. This section is filled by `-Zprofile`.

**Comment by jschwe** [comment]
Okay, I think I'm getting closer to the problem.
- I'm now getting a `.gcno` file for the application I want to instrument.
- I'm still getting `NoCoverageData`. Additionally the .init_array section doesn't exist in my executable.
```bash
$ objdump -s -j .init_array target/x86_64-unknown-hermit/debug/rusty_demo

target/x86_64-unknown-hermit/debug/rusty_demo:     file format elf64-x86-64

objdump: section '.init_array' mentioned in a -j option, but not found in any input file
```
- I am compiling with `-Zno-profiler-runtime` as recommended in your readme. Is this correct? I looked into the source code for `profiler_builtins`, which is built, when I remove `-Zno-profiler-runtime` and add `profiler_builtins` to my `build_std` argument. It builds C code from rust/src/llvm-project/compiler-rt. Looking into your library you only provide the public functions llvm_gcda_xxx etc. How does the profiling work without the compiler-rt functions? I'm using a custom target so I'm assuming that I might have to build compiler-rt for my target. 
- Could you clarify if the functions provided by the `InstrProfilingXXX` files in `compiler-rt/profile` are needed, or if your crate provides them in some way and I just didn't notice.

**Comment by Amanieu** [comment]
- You should have a .gcno for every crate in your project.

- Are you using a custom linker script? Make sure it includes the `.init_array` section:
```
  .init_array : {
	__init_array_start = .;
	KEEP(*(SORT(.init_array.*)))
	__init_array_end = .;
  }
```

- The default profiling runtime uses libc and does file I/O to read the .gcno files and write to the .gcda files. minicov implements the public API of the profiler runtime (`llvm_gcda_*`), serializes the profiling data and then replays the profiling data on the host with `cargo minicov`.

- Only the `llvm_gcda_*` functions provided by the minicov crate are needed.

**Comment by jschwe** [comment]
- I'm using a RUSTC_WRAPPER to only pass the -Zprofile flag to the crate I want to instrument. So that is working as intended i think
- I'm not using any custom linker script.
- This is actually very helpful. I don't have libc, so that is probably part of the issue.

Thanks again for your help. I'm closing this issue, since it doesn't have much to do with your crate.

**Comment by Amanieu** [comment]
To be clar, minicov itself doesn't depend on libc or on Rust's default profiling runtime. So you don't need libc to use minicov: it should work for your use case.

If you are still missing the `.init_array` section you may want to check if this section is present in the `.o` or `.rlib` files generated by LLVM in the `target` directory. I suspect there may be an issue with your linker (or its default linker script?) that doesn't preserve the `.init_array` section.
