### ISSUE TITLE
Custom flags for compilation of C files 

### ISSUE THREAD

**Issue by Nils-TUD** [Amanieu/minicov#10]
Is it possible to specify additional compiler flags when building the C files?

The specific problem I have on x86-64 (there is also a problem on RISC-V, but that could also be solved with custom flags) is that the C files are build with FPU instructions, which causes trouble at runtime. In my target specification, soft-float is enabled and MMX/SSE are disabled, but this is apparently not passed to clang.

**Comment by Amanieu** [comment]
You can use `TARGET_CFLAGS`/`TARGET_CXXFLAGS` environment variables to pass additional flags.

https://github.com/rust-lang/cc-rs#external-configuration-via-environment-variables

**Comment by Nils-TUD** [comment]
Great, thanks!

Maybe it makes sense to add the link to your README, for people like me that haven't used the cc crate before? :)
