### ISSUE TITLE
Potential support for no_alloc crates

### ISSUE THREAD

**Issue by xd009642** [Amanieu/minicov#2]
So I was working on a similar thing until I came across the profiler-builtins requirement and then upon this crate. My initial approach was going to go for either no_alloc or alloc based on a feature where users could specify using an env var a maximum profraw size (since the size is static after compilation you can always try it once, fail and see what size to set it to).

I did this via a build script as so:

```rust
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let size = env::var("COVERAGE_BUFFER_SIZE")
        .map(|x| x.parse::<usize>().unwrap_or(1024))
        .unwrap_or(1024);

    let output = Path::new(&env::var_os("OUT_DIR").unwrap()).join("constants.rs");

    fs::write(
        &output,
        format!("pub const COVERAGE_BUFFER_SIZE: usize = {};", size),
    )
    .unwrap();
}
```

I was wondering if you'd be open to this as a non-default feature? It's obviously less ergonomic than simply having alloc but it could be useful to some users

**Comment by Amanieu** [comment]
Sure! I'd be happy to have a non-alloc API (with `alloc` as an enabled-by-default feature). I would like to avoid environment variables since that introduces an OS dependency. Instead we can just have an API which returns `__llvm_profile_get_size_for_buffer` and another one that takes a slice of the right length.

**Comment by xd009642** [comment]
Okay I'll work on a pr, though one clarification the way I've done the env var is so it's used at build time to generate a constant. So you only need an OS on the machine you run rustc (which is also a given)
