### ISSUE TITLE
Code coverage report is empty

### ISSUE THREAD

**Issue by Nils-TUD** [Amanieu/minicov#9]
I'm trying to use minicov for my `no_std` project and did so as described in the README. I can successfully build my program using the minicov crate as a dependency and can also run it. At the end, my program uses `minicov::capture_coverage` to write out a ~2.4 MB file.

However, when I afterwards generate a human readable report from that file, the report is empty. I've tried both `grcov` as used in the README and `llvm-cov`. In the case of `grcov` "empty" means that the generated website has an empty table of directories and `grcov` doesn't print anything on stdout/stderr (not even with `--log-level=TRACE`). In the case of `llvm-cov` "empty" means that it doesn't write anything to stdout/stderr.

I assume/hope that there would be some error message in case of a corrupted file, version mismatch, or anything like that. Since there isn't, but the result is simply empty, I'm a bit lost.

Does anybody have an idea?

**Comment by Amanieu** [comment]
Can you try the minicov-test program in this repo? If this works then the problem is likely in your code. If this still fails then the problem might be in your toolchain (are you on the latest nightly? what is the version of llvm-cov/grcov?)

```
RUSTFLAGS="-Cinstrument-coverage -Zno-profiler-runtime" cargo run --target=x86_64-unknown-linux-gnu
grcov -t html output.profraw -b target/x86_64-unknown-linux-gnu/debug/minicov-test
```

**Comment by Nils-TUD** [comment]
I've just tried it. The result is also empty.

I'm using Rust nightly-2022-09-12-x86_64-unknown-linux-gnu, grcov 0.8.11, and llvm-cov from the Rust nightly toolchain (15.0.0-rust-1.65.0-nightly).

**Comment by Amanieu** [comment]
So here's what I get after further testing:
- grcov seems to be broken and doesn't produce output.
- Using llvm-profdata & llvm-cov directly does seem to work correctly.

```
llvm-profdata merge -sparse output.profraw -o output.profdata
llvm-cov show target/x86_64-unknown-linux-gnu/debug/minicov-test -instr-profile=output.profdata
```

I think this might be a bug in grcov, minicov itself seems to be working correctly.

**Comment by Amanieu** [comment]
I found out what the problem is: you need to add `-s .` to the grcov arguments to specify the source directory.

**Comment by Nils-TUD** [comment]
Oh, I just noticed that I accidentally filtered by name with llvm-cov and that's why the result was empty m(

And yes, it was indeed the missing `-s .` for grcov. Now it works both with minicov and my own project :)

Thanks a lot for your help!
